window.surface_mapping = {
    'missing': { text: document.getElementById('missing-text').innerText, color: '#d1d1d1' },
    'paved': { text: document.getElementById('paved-text').innerText, color: '#8c8c8c' },
    'unpaved': { text: document.getElementById('unpaved-text').innerText, color: '#6b443a' },
    'asphalt': { text: document.getElementById('asphalt-text').innerText, color: '#8c8c8c' },
    'concrete': { text: document.getElementById('concrete-text').innerText, color: '#8c8c8c' },
    'chipseal': { text: document.getElementById('chipseal-text').innerText, color: '#8c8c8c' },
    'cobblestone': { text: document.getElementById('cobblestone-text').innerText, color: '#ffd991' },
    'unhewn_cobblestone': { text: document.getElementById('unhewn-cobblestone-text').innerText, color: '#ffd991' },
    'paving_stones': { text: document.getElementById('paving-stones-text').innerText, color: '#8c8c8c' },
    'stepping_stones': { text: document.getElementById('stepping-stones-text').innerText, color: '#c7b2db' },
    'sett': { text: document.getElementById('sett-text').innerText, color: '#ffd991' },
    'metal': { text: document.getElementById('metal-text').innerText, color: '#8c8c8c' },
    'wood': { text: document.getElementById('wood-text').innerText, color: '#6b443a' },
    'compacted': { text: document.getElementById('compacted-text').innerText, color: '#ffffa8' },
    'fine_gravel': { text: document.getElementById('fine-gravel-text').innerText, color: '#ffffa8' },
    'gravel': { text: document.getElementById('gravel-text').innerText, color: '#ffffa8' },
    'pebblestone': { text: document.getElementById('pebblestone-text').innerText, color: '#ffffa8' },
    'rock': { text: document.getElementById('rock-text').innerText, color: '#ffd991' },
    'dirt': { text: document.getElementById('dirt-text').innerText, color: '#ffffa8' },
    'ground': { text: document.getElementById('ground-text').innerText, color: '#6b443a' },
    'earth': { text: document.getElementById('earth-text').innerText, color: '#6b443a' },
    'snow': { text: document.getElementById('snow-text').innerText, color: '#bdfffc' },
    'ice': { text: document.getElementById('ice-text').innerText, color: '#bdfffc' },
    'salt': { text: document.getElementById('salt-text').innerText, color: '#b6c0f2' },
    'mud': { text: document.getElementById('mud-text').innerText, color: '#6b443a' },
    'sand': { text: document.getElementById('sand-text').innerText, color: '#ffffc4' },
    'woodchips': { text: document.getElementById('woodchips-text').innerText, color: '#6b443a' },
    'grass': { text: document.getElementById('grass-text').innerText, color: '#61b55c' },
    'grass_paver': { text: document.getElementById('grass-paver-text').innerText, color: '#61b55c' }
};

window.slope_mapping = {
    '-6': { text: '<-25%', color: '#046307', min: -Infinity, max: -25.5 },
    '-5': { text: '[-25,-17]%', color: '#028306', min: -25.5, max: -16.5 },
    '-4': { text: '[-16,-13]%', color: '#2AA12E', min: -16.5, max: -12.5 },
    '-3': { text: '[-12,-9]%', color: '#53BF56', min: -12.5, max: -8.5 },
    '-2': { text: '[-8,-5]%', color: '#7BDD7E', min: -8.5, max: -4.5 },
    '-1': { text: '[-4,-2]%', color: '#A4FBA6', min: -4.5, max: -1.5 },
    '0': { text: '[-1,1]%', color: '#edf0bd', min: -1.5, max: 1.5 },
    '1': { text: '[2,4]%', color: '#ffcc99', min: 1.5, max: 4.5 },
    '2': { text: '[5,8]%', color: '#F29898', min: 4.5, max: 8.5 },
    '3': { text: '[9,12]%', color: '#E07575', min: 8.5, max: 12.5 },
    '4': { text: '[13,16]%', color: '#CF5352', min: 12.5, max: 16.5 },
    '5': { text: '[17,25]%', color: '#BE312F', min: 16.5, max: 25.5 },
    '6': { text: '>25%', color: '#AD0F0C', min: 25.5, max: Infinity }
};

window.icons = [
    [" ",{prefix: "", glyph: ""}],
    ["ATV",{prefix: "", glyph: ""}],
	["Airport",{prefix: "fas", glyph: "plane"}],
	["Amusement Park",{prefix: "", glyph: ""}],
	["Anchor",{prefix: "fas", glyph: "anchor"}],
	["Anchor Prohibited",{prefix: "", glyph: ""}],
	["Animal Tracks",{prefix: "fas", glyph: "paw"}],
	["Asian Food",{prefix: "fas", glyph: "utensils"}],
	["Bait and Tackle",{prefix: "", glyph: ""}],
	["Ball Park",{prefix: "fas", glyph: "futbol"}],
	["Bank",{prefix: "fas", glyph: "dollar-sign"}],
	["Bar",{prefix: "fas", glyph: "beer"}],
	["Beach",{prefix: "fas", glyph: "umbrella-beach"}],
	["Beacon",{prefix: "", glyph: ""}],
	["Bell",{prefix: "fas", glyph: "bell"}],
	["Big Game",{prefix: "fas", glyph: "dice"}],
	["Bike Trail",{prefix: "fas", glyph: "biking"}],
	["Blind",{prefix: "fas", glyph: "blind"}],
	["Block, Blue",{prefix: "fas", glyph: "cube"}],
	["Block, Green",{prefix: "fas", glyph: "cube"}],
	["Block, Red",{prefix: "fas", glyph: "cube"}],
	["Blood Trail",{prefix: "", glyph: ""}],
	["Boat Ramp",{prefix: "fas", glyph: "ship"}],
	["Border Crossing (Port Of Entry)",{prefix: "", glyph: ""}],
	["Bottom Conditions",{prefix: "", glyph: ""}],
	["Bowling",{prefix: "fas", glyph: "bowling-ball"}],
	["Bridge",{prefix: "fas", glyph: "archway"}],
	["Building",{prefix: "fas", glyph: "building"}],
	["Buoy, White",{prefix: "fas", glyph: "life-ring"}],
	["Campground",{prefix: "fas", glyph: "campground"}],
	["Car",{prefix: "fas", glyph: "car-side"}],
	["Car Rental",{prefix: "fas", glyph: "car-side"}],
	["Car Repair",{prefix: "fas", glyph: "tools"}],
	["Cemetery",{prefix: "fas", glyph: "cross"}],
	["Church",{prefix: "fas", glyph: "place-of-worship"}],
	["Circle with X",{prefix: "fas", glyph: "times-circle"}],
	["Circle, Blue",{prefix: "fas", glyph: "circle"}],
	["Circle, Green",{prefix: "fas", glyph: "circle"}],
	["Circle, Red",{prefix: "fas", glyph: "circle"}],
	["City (Capitol)",{prefix: "fas", glyph: "city"}],
	["City (Large)",{prefix: "fas", glyph: "city"}],
	["City (Medium)",{prefix: "fas", glyph: "city"}],
	["City (Small)",{prefix: "fas", glyph: "city"}],
	["City Hall",{prefix: "fas", glyph: "landmark"}],
	["Civil",{prefix: "fas", glyph: "male"}],
	["Coast Guard",{prefix: "fas", glyph: "life-ring"}],
	["Contact, Afro",{prefix: "fas", glyph: "info"}],
	["Contact, Alien",{prefix: "fas", glyph: "info"}],
	["Contact, Ball Cap",{prefix: "fas", glyph: "info"}],
	["Contact, Big Ears",{prefix: "fas", glyph: "info"}],
	["Contact, Biker",{prefix: "fas", glyph: "info"}],
	["Contact, Blonde",{prefix: "fas", glyph: "info"}],
	["Contact, Bug",{prefix: "fas", glyph: "info"}],
	["Contact, Cat",{prefix: "fas", glyph: "info"}],
	["Contact, Clown",{prefix: "fas", glyph: "info"}],
	["Contact, Dog",{prefix: "fas", glyph: "info"}],
	["Contact, Dreadlocks",{prefix: "fas", glyph: "info"}],
	["Contact, Female1",{prefix: "fas", glyph: "info"}],
	["Contact, Female2",{prefix: "fas", glyph: "info"}],
	["Contact, Female3",{prefix: "fas", glyph: "info"}],
	["Contact, Glasses",{prefix: "fas", glyph: "info"}],
	["Contact, Goatee",{prefix: "fas", glyph: "info"}],
	["Contact, Kung-Fu",{prefix: "fas", glyph: "info"}],
	["Contact, Panda",{prefix: "fas", glyph: "info"}],
	["Contact, Pig",{prefix: "fas", glyph: "info"}],
	["Contact, Pirate",{prefix: "fas", glyph: "info"}],
	["Contact, Ranger",{prefix: "fas", glyph: "info"}],
	["Contact, Smiley",{prefix: "fas", glyph: "info"}],
	["Contact, Spike",{prefix: "fas", glyph: "info"}],
	["Contact, Sumo",{prefix: "fas", glyph: "info"}],
	["Controlled Area",{prefix: "fas", glyph: "exclamation"}],
	["Convenience Store",{prefix: "fas", glyph: "store"}],
	["Cover",{prefix: "", glyph: ""}],
	["Covey",{prefix: "", glyph: ""}],
	["Crossing",{prefix: "fas", glyph: "traffic-light"}],
	["Dam",{prefix: "fas", glyph: "water"}],
	["Danger Area",{prefix: "fas", glyph: "exclamation"}],
	["Deli",{prefix: "fas", glyph: "store"}],
	["Department Store",{prefix: "fas", glyph: "cart-shopping"}],
	["Diamond, Blue",{prefix: "fas", glyph: "gem"}],
	["Diamond, Green",{prefix: "fas", glyph: "gem"}],
	["Diamond, Red",{prefix: "fas", glyph: "gem"}],
	["Diver Down Flag 1",{prefix: "fas", glyph: "flag"}],
	["Diver Down Flag 2",{prefix: "fas", glyph: "flag"}],
	["Dock",{prefix: "fas", glyph: "anchor"}],
	["Dot, White",{prefix: "fas", glyph: "circle"}],
	["Drinking Water",{prefix: "fas", glyph: "faucet"}],
	["Dropoff",{prefix: "", glyph: ""}],
	["Elevation point",{prefix: "fas", glyph: "mountain"}],
	["Event Cache",{prefix: "fas", glyph: "search"}],
	["Exit",{prefix: "fas", glyph: "door-open"}],
	["Exit without services",{prefix: "fas", glyph: "door-open"}],
	["Fast Food",{prefix: "fas", glyph: "hamburger"}],
	["First approach fix",{prefix: "", glyph: ""}],
	["Fishing Area",{prefix: "fas", glyph: "fish"}],
	["Fishing Hot Spot Facility",{prefix: "fas", glyph: "fish"}],
	["Fitness Center",{prefix: "fas", glyph: "dumbbell"}],
	["Flag",{prefix: "fas", glyph: "flag"}],
	["Flag, Blue",{prefix: "fas", glyph: "flag"}],
	["Flag, Green",{prefix: "fas", glyph: "flag"}],
	["Flag, Red",{prefix: "fas", glyph: "flag"}],
	["Food Source",{prefix: "fas", glyph: "seedling"}],
	["Forest",{prefix: "fas", glyph: "tree"}],
	["Furbearer",{prefix: "fas", glyph: "paw"}],
	["Gambling/casino",{prefix: "fas", glyph: "dice"}],
	["Gas Station",{prefix: "fas", glyph: "gas-pump"}],
	["Geocache",{prefix: "fas", glyph: "search"}],
	["Geocache Found",{prefix: "fas", glyph: "search"}],
	["Geographic place name, Man-made",{prefix: "fas", glyph: "building"}],
	["Geographic place name, land",{prefix: "fas", glyph: "globe-europe"}],
	["Geographic place name, water",{prefix: "fas", glyph: "water"}],
	["Ghost Town",{prefix: "fas", glyph: "city"}],
	["Glider Area",{prefix: "fas", glyph: "plane"}],
	["Golf Course",{prefix: "fas", glyph: "golf-ball"}],
	["Ground Transportation",{prefix: "fas", glyph: "subway"}],
	["Heliport",{prefix: "fas", glyph: "helicopter"}],
	["Horn",{prefix: "fas", glyph: "bullhorn"}],
	["Hotel",{prefix: "fas", glyph: "hotel"}],
	["House",{prefix: "fas", glyph: "home"}],
	["Hunting Area",{prefix: "fas", glyph: "paw"}],
	["Ice Skating",{prefix: "fas", glyph: "skating"}],
	["Information",{prefix: "fas", glyph: "info"}],
	["Intersection",{prefix: "fas", glyph: "traffic-light"}],
	["Intl freeway hwy",{prefix: "fas", glyph: "road"}],
	["Intl national hwy",{prefix: "fas", glyph: "road"}],
	["Italian food",{prefix: "fas", glyph: "pizza"}],
	["Large Ramp intersection",{prefix: "fas", glyph: "traffic-light"}],
	["Large exit without services",{prefix: "fas", glyph: "door-open"}],
	["Letter A, Blue",{prefix: "", glyph: "A"}],
	["Letter A, Green",{prefix: "", glyph: "A"}],
	["Letter A, Red",{prefix: "", glyph: "A"}],
	["Letter B, Blue",{prefix: "", glyph: "B"}],
	["Letter B, Green",{prefix: "", glyph: "B"}],
	["Letter B, Red",{prefix: "", glyph: "B"}],
	["Letter C, Blue",{prefix: "", glyph: "C"}],
	["Letter C, Green",{prefix: "", glyph: "C"}],
	["Letter C, Red",{prefix: "", glyph: "C"}],
	["Letter D, Blue",{prefix: "", glyph: "D"}],
	["Letter D, Green",{prefix: "", glyph: "D"}],
	["Letter D, Red",{prefix: "", glyph: "D"}],
	["Letterbox Cache",{prefix: "fas", glyph: "box-open"}],
	["Levee",{prefix: "fas", glyph: "anchor"}],
	["Library",{prefix: "fas", glyph: "book"}],
	["Light",{prefix: "fas", glyph: "lightbulb"}],
	["Live Theater",{prefix: "fas", glyph: "theater-masks"}],
	["Localizer Outer Marker",{prefix: "fas", glyph: "crosshairs"}],
	["Locationless (Reverse) Cache",{prefix: "fas", glyph: "search"}],
	["Lodge",{prefix: "fas", glyph: "bed"}],
	["Lodging",{prefix: "fas", glyph: "bed"}],
	["Man Overboard",{prefix: "", glyph: ""}],
	["Marina",{prefix: "fas", glyph: "anchor"}],
	["Medical Facility",{prefix: "fas", glyph: "clinic-medical"}],
	["Micro-Cache",{prefix: "fas", glyph: "search"}],
	["Mile Marker",{prefix: "fas", glyph: "ruler-horizontal"}],
	["Military",{prefix: "fas", glyph: "fighter-jet"}],
	["Mine",{prefix: "fas", glyph: "bomb"}],
	["Missed approach point",{prefix: "", glyph: ""}],
	["Movie Theater",{prefix: "fas", glyph: "film"}],
	["Multi-Cache",{prefix: "fas", glyph: "search"}],
	["Museum",{prefix: "fas", glyph: "monument"}],
	["Navaid, Amber",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Black",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Blue",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Green",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Green/Red",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Green/White",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Orange",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Red",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Red/Green",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Red/White",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, Violet",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, White",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, White/Green",{prefix: "fas", glyph: "drafting-compass"}],
	["Navaid, White/Red",{prefix: "fas", glyph: "drafting-compass"}],
	["Non-directional beacon",{prefix: "", glyph: ""}],
	["Null",{prefix: "", glyph: ""}],
	["Number 0, Blue",{prefix: "", glyph: "0"}],
	["Number 0, Green",{prefix: "", glyph: "0"}],
	["Number 0, Red",{prefix: "", glyph: "0"}],
	["Number 1, Blue",{prefix: "", glyph: "1"}],
	["Number 1, Green",{prefix: "", glyph: "1"}],
	["Number 1, Red",{prefix: "", glyph: "1"}],
	["Number 2, Blue",{prefix: "", glyph: "2"}],
	["Number 2, Green",{prefix: "", glyph: "2"}],
	["Number 2, Red",{prefix: "", glyph: "2"}],
	["Number 3, Blue",{prefix: "", glyph: "3"}],
	["Number 3, Green",{prefix: "", glyph: "3"}],
	["Number 3, Red",{prefix: "", glyph: "3"}],
	["Number 4, Blue",{prefix: "", glyph: "4"}],
	["Number 4, Green",{prefix: "", glyph: "4"}],
	["Number 4, Red",{prefix: "", glyph: "4"}],
	["Number 5, Blue",{prefix: "", glyph: "5"}],
	["Number 5, Green",{prefix: "", glyph: "5"}],
	["Number 5, Red",{prefix: "", glyph: "5"}],
	["Number 6, Blue",{prefix: "", glyph: "6"}],
	["Number 6, Green",{prefix: "", glyph: "6"}],
	["Number 6, Red",{prefix: "", glyph: "6"}],
	["Number 7, Blue",{prefix: "", glyph: "7"}],
	["Number 7, Green",{prefix: "", glyph: "7"}],
	["Number 7, Red",{prefix: "", glyph: "7"}],
	["Number 8, Blue",{prefix: "", glyph: "8"}],
	["Number 8, Green",{prefix: "", glyph: "8"}],
	["Number 8, Red",{prefix: "", glyph: "8"}],
	["Number 9, Blue",{prefix: "", glyph: "9"}],
	["Number 9, Green",{prefix: "", glyph: "9"}],
	["Number 9, Red",{prefix: "", glyph: "9"}],
	["Oil Field",{prefix: "fas", glyph: "oil-can"}],
	["Open 24 Hours",{prefix: "", glyph: ""}],
	["Oval, Blue",{prefix: "fas", glyph: "circle"}],
	["Oval, Green",{prefix: "fas", glyph: "circle"}],
	["Oval, Red",{prefix: "fas", glyph: "circle"}],
	["Parachute Area",{prefix: "fas", glyph: "parachute-box"}],
	["Park",{prefix: "fas", glyph: "tree"}],
	["Parking Area",{prefix: "fas", glyph: "parking"}],
	["Pharmacy",{prefix: "fas", glyph: "first-aid"}],
	["Picnic Area",{prefix: "fas", glyph: "utensils"}],
	["Pin, Blue",{prefix: "fas", glyph: "map-pin"}],
	["Pin, Green",{prefix: "fas", glyph: "map-pin"}],
	["Pin, Red",{prefix: "fas", glyph: "map-pin"}],
	["Pizza",{prefix: "fas", glyph: "pizza"}],
	["Police Station",{prefix: "fas", glyph: "shield-alt"}],
	["Post Office",{prefix: "fas", glyph: "envelope"}],
	["Private Field",{prefix: "fas", glyph: "lock"}],
	["Puzzle Cache",{prefix: "fas", glyph: "search"}],
	["RV Park",{prefix: "fas", glyph: "caravan"}],
	["Radio Beacon",{prefix: "", glyph: ""}],
	["Ramp intersection",{prefix: "fas", glyph: "traffic-light"}],
	["Rectangle, Blue",{prefix: "fas", glyph: "square"}],
	["Rectangle, Green",{prefix: "fas", glyph: "square"}],
	["Rectangle, Red",{prefix: "fas", glyph: "square"}],
	["Reef",{prefix: "fas", glyph: "exclamation"}],
	["Residence",{prefix: "fas", glyph: "home"}],
	["Restaurant",{prefix: "fas", glyph: "utensils"}],
	["Restricted Area",{prefix: "fas", glyph: "exclamation"}],
	["Restroom",{prefix: "fas", glyph: "restroom"}],
	["Road",{prefix: "fas", glyph: "road"}],
	["Scales",{prefix: "fas", glyph: "balance-scale"}],
	["Scenic Area",{prefix: "fas", glyph: "binoculars"}],
	["School",{prefix: "fas", glyph: "graduation-cap"}],
	["Seafood",{prefix: "fas", glyph: "fish"}],
	["Seaplane Base",{prefix: "fas", glyph: "plane"}],
	["Shipwreck",{prefix: "fas", glyph: "ship"}],
	["Shopping Center",{prefix: "fas", glyph: "shopping-cart"}],
	["Short Tower",{prefix: "", glyph: ""}],
	["Shower",{prefix: "fas", glyph: "shower"}],
	["Ski Resort",{prefix: "fas", glyph: "skiing"}],
	["Skiing Area",{prefix: "fas", glyph: "skiing"}],
	["Skull and Crossbones",{prefix: "fas", glyph: "skull-crossbones"}],
	["Small City",{prefix: "fas", glyph: "city"}],
	["Small Game",{prefix: "fas", glyph: "dice"}],
	["Soft Field",{prefix: "", glyph: ""}],
	["Square, Blue",{prefix: "fas", glyph: "square"}],
	["Square, Green",{prefix: "fas", glyph: "square"}],
	["Square, Red",{prefix: "fas", glyph: "square"}],
	["Stadium",{prefix: "fas", glyph: "futbol"}],
	["State Hwy",{prefix: "fas", glyph: "road"}],
	["Steak",{prefix: "fas", glyph: "utensils"}],
	["Street Intersection",{prefix: "fas", glyph: "traffic-light"}],
	["Stump",{prefix: "", glyph: ""}],
	["Summit",{prefix: "fas", glyph: "mountain"}],
	["Swimming Area",{prefix: "fas", glyph: "swimmer"}],
	["TACAN",{prefix: "fas", glyph: "fighter-jet"}],
	["Tall Tower",{prefix: "", glyph: ""}],
	["Telephone",{prefix: "fas", glyph: "phone"}],
	["Tide/Current PRediction Station",{prefix: "", glyph: ""}],
	["Toll Booth",{prefix: "", glyph: ""}],
	["TracBack Point",{prefix: "", glyph: ""}],
	["Trail Head",{prefix: "", glyph: ""}],
	["Tree Stand",{prefix: "", glyph: ""}],
	["Treed Quarry",{prefix: "", glyph: ""}],
	["Triangle, Blue",{prefix: "", glyph: ""}],
	["Triangle, Green",{prefix: "", glyph: ""}],
	["Triangle, Red",{prefix: "", glyph: ""}],
	["Truck",{prefix: "fas", glyph: "truck"}],
	["Truck Stop",{prefix: "fas", glyph: "truck"}],
	["Tunnel",{prefix: "fas", glyph: "archway"}],
	["U Marina",{prefix: "fas", glyph: "anchor"}],
	["U stump",{prefix: "", glyph: ""}],
	["US hwy",{prefix: "fas", glyph: "road"}],
	["Ultralight Area",{prefix: "", glyph: ""}],
	["Unknown Cache",{prefix: "fas", glyph: "search"}],
	["Upland Game",{prefix: "", glyph: ""}],
	["VHF Omni-range",{prefix: "fas", glyph: "fighter-jet"}],
	["VOR-DME",{prefix: "fas", glyph: "fighter-jet"}],
	["VOR/TACAN",{prefix: "fas", glyph: "fighter-jet"}],
	["Virtual cache",{prefix: "fas", glyph: "search"}],
	["Water Hydrant",{prefix: "fas", glyph: "tint"}],
	["Water Source",{prefix: "fas", glyph: "faucet"}],
	["Waterfowl",{prefix: "", glyph: ""}],
	["Waypoint",{prefix: "fas", glyph: "map-sign"}],
	["Webcam Cache",{prefix: "fas", glyph: "camera"}],
	["Weed Bed",{prefix: "fas", glyph: "bed"}],
	["Winery",{prefix: "fas", glyph: "wine-glass"}],
	["Wrecker",{prefix: "", glyph: ""}],
	["Zoo",{prefix: "fas", glyph: "paw"}]
];

class PointOfInterest {
	constructor(name, query, glyph, sym) {
		this.name = name;
		this.query = query;
		this.glyph = glyph;
        this.sym = sym; // taken from the list above
	}
}
pointsOfInterest = {}
pointsOfInterest[document.getElementById('eat-and-drink-text').innerText] = [
	new PointOfInterest(document.getElementById('bakery-text').innerText, "['shop'='bakery']", "bread-slice", "Convenience Store"),
	new PointOfInterest(document.getElementById('supermarket-text').innerText, "['shop'='supermarket']", "cart-shopping", "Department Store"),
	new PointOfInterest(document.getElementById('convenience-store-text').innerText, "['shop'='convenience']", "store", "Convenience Store"),
	new PointOfInterest(document.getElementById('restaurant-text').innerText, "['amenity'='restaurant']", "utensils", "Restaurant"),
	new PointOfInterest(document.getElementById('fast-food-text').innerText, "['amenity'='fast_food']", "burger", "Fast Food"),
	new PointOfInterest(document.getElementById('cafe-text').innerText, "['amenity'='cafe']", "mug-hot", "Restaurant"),
	new PointOfInterest(document.getElementById('pub-text').innerText, "['amenity'='pub']", "beer-mug-empty", "Bar"),
	new PointOfInterest(document.getElementById('bar-text').innerText, "['amenity'='bar']", "martini-glass", "Bar"),
];
pointsOfInterest[document.getElementById('amenities-text').innerText] = [
	new PointOfInterest(document.getElementById('toilets-text').innerText, "['amenity'='toilets']", "restroom", "Restroom"),
	new PointOfInterest(document.getElementById('drinking-water-text').innerText, "['amenity'='drinking_water']", "faucet", "Drinking Water"),
	new PointOfInterest(document.getElementById('water-point-text').innerText, "['amenity'='water_point']", "faucet", "Drinking Water"),
	new PointOfInterest(document.getElementById('water-spring-text').innerText, "['natural'='spring']['drinking_water'='yes']", "droplet", "Water Source"),
	new PointOfInterest(document.getElementById('shower-text').innerText, "['amenity'='shower']", "shower", "Shower"),
	new PointOfInterest(document.getElementById('fuel-station-text').innerText, "['amenity'='fuel']", "gas-pump", "Gas Station"),
	new PointOfInterest(document.getElementById('parking-text').innerText, "['amenity'='parking']", "square-parking", "Parking Area"),
    new PointOfInterest(document.getElementById('barrier-text').innerText, "['barrier']", "road-barrier", "Crossing"),
];
pointsOfInterest[document.getElementById('tourism-text').innerText] = [
	new PointOfInterest(document.getElementById('attraction-text').innerText, "['tourism'='attraction']", "landmark", "Amusement Park"),
	new PointOfInterest(document.getElementById('viewpoint-text').innerText, "['tourism'='viewpoint']", "binoculars", "Scenic Area"),
	new PointOfInterest(document.getElementById('hotel-text').innerText, "['tourism'='hotel']", "hotel", "Hotel"),
	new PointOfInterest(document.getElementById('hostel-text').innerText, "['tourism'='hostel']", "bed", "Hotel"),
	new PointOfInterest(document.getElementById('guest-house-text').innerText, "['tourism'='guest_house']", "house-chimney-user", "Lodge"),
	new PointOfInterest(document.getElementById('motel-text').innerText, "['tourism'='motel']", "hotel", "Hotel"),
	new PointOfInterest(document.getElementById('campsite-text').innerText, "['tourism'='campsite']", "campground", "Campground"),
	new PointOfInterest(document.getElementById('alpine-hut-text').innerText, "['tourism'='alpine_hut']", "house-chimney-crack", "Lodge"),
	new PointOfInterest(document.getElementById('wilderness-hut-text').innerText, "['tourism'='wilderness_hut']", "house-crack", "Lodge"),
	new PointOfInterest(document.getElementById('climbing-text').innerText, "['sport'='climbing']", "mountain", "Elevation point"),
];
pointsOfInterest[document.getElementById('bicycle-text').innerText] = [
	new PointOfInterest(document.getElementById('bicycle-parking-text').innerText, "['amenity'='bicycle_parking']", "square-parking", "Parking Area"),
	new PointOfInterest(document.getElementById('bicycle-rental-text').innerText, "['amenity'='bicycle_rental']", "tag", "Bike Trail"),
	new PointOfInterest(document.getElementById('bicycle-shop-text').innerText, "['shop'='bicycle']", "bicycle", "Bike Trail"),
];
pointsOfInterest[document.getElementById('public-transport-text').innerText] = [
	new PointOfInterest(document.getElementById('railway-station-text').innerText, "['railway'='station']", "train", "Ground Transportation"),
	new PointOfInterest(document.getElementById('tram-stop-text').innerText, "['railway'='tram_stop']", "train-tram", "Ground Transportation"),
	new PointOfInterest(document.getElementById('bus-stop-text').innerText, "['public_transport'='stop_position']['bus'='yes']", "bus-simple", "Ground Transportation"),
	new PointOfInterest(document.getElementById('ferry-text').innerText, "['amenity'='ferry_terminal']", "ship", "Boat Ramp"),
];
